import type { CSSProperties } from "react";

const border = "1px solid var(--border-card)";
const divider = "1px solid var(--border-subtle)";
const caption = "var(--primary)";

export const titleReportStyles = {
  badge(background: string | null, color: string | null): CSSProperties {
    return {
      background: background || "var(--gray-200)",
      borderRadius: "9999rem",
      color: color || "var(--title-ink)",
      display: "inline-block",
      fontSize: "0.875rem",
      fontWeight: 600,
      lineHeight: 1.2,
      padding: "0.25rem 0.5rem",
      whiteSpace: "nowrap",
    };
  },
  caption: {
    color: caption,
    fontWeight: 700,
    padding: "0.5rem 0",
    textAlign: "left",
  } satisfies CSSProperties,
  chainBody: {
    display: "flex",
    flexDirection: "column",
    gap: "1rem",
    padding: "0.35rem 1rem 1rem",
  } satisfies CSSProperties,
  chainList: {
    display: "flex",
    flexDirection: "column",
    gap: "0.875rem",
    width: "100%",
  } satisfies CSSProperties,
  chainSection: {
    background: "var(--white)",
    border,
    borderRadius: "var(--radius-card)",
    boxShadow: "var(--shadow-card)",
    margin: 0,
    overflow: "hidden",
  } satisfies CSSProperties,
  chainTrigger: {
    background: "var(--gray-100)",
    border: 0,
    borderBottom: border,
    color: "var(--title-ink)",
    cursor: "pointer",
    display: "block",
    font: "inherit",
    fontSize: "1.07rem",
    fontWeight: 700,
    lineHeight: 1.4,
    minHeight: "2.75rem",
    padding: "0.65rem 1rem",
    textAlign: "left",
    width: "100%",
    wordBreak: "break-word",
  } satisfies CSSProperties,
  count: {
    color: "var(--slate-500)",
    fontSize: "0.95rem",
    whiteSpace: "nowrap",
  } satisfies CSSProperties,
  detailLabel: {
    color: "var(--slate-500)",
    fontSize: "0.75rem",
    fontWeight: 600,
    marginTop: "0.5rem",
  } satisfies CSSProperties,
  empty: {
    color: "var(--body-ink)",
    fontSize: "1rem",
  } satisfies CSSProperties,
  header: {
    alignItems: "baseline",
    borderBottom: "1px solid var(--border-card)",
    boxSizing: "border-box",
    display: "flex",
    flex: "0 0 auto",
    flexWrap: "wrap",
    gap: "var(--panel-header-gap)",
    justifyContent: "space-between",
    minHeight: "var(--panel-header-height)",
    padding: "var(--panel-header-padding)",
    width: "100%",
  } satisfies CSSProperties,
  headerActions: {
    alignItems: "center",
    display: "flex",
    flexWrap: "wrap",
    gap: "0.75rem",
    justifyContent: "flex-end",
  } satisfies CSSProperties,
  infoBody(color: string): CSSProperties {
    return {
      background: "var(--paper-tint)",
      border: `1px solid ${color}`,
      borderLeft: `0.25rem solid ${color}`,
      borderRadius: "var(--radius-card)",
      color: "var(--title-ink)",
      fontSize: "0.95rem",
      lineHeight: 1.5,
      padding: "1rem",
      textAlign: "left",
    };
  },
  issueEmpty: {
    background: "var(--paper-tint)",
    color: caption,
    fontWeight: 700,
    margin: "0.5rem 0",
    padding: "0.5rem 0",
    textAlign: "left",
  } satisfies CSSProperties,
  link: {
    background: "transparent",
    border: 0,
    color: "var(--primary-dark)",
    cursor: "pointer",
    font: "inherit",
    fontSize: "0.9375rem",
    padding: 0,
    textDecoration: "underline",
  } satisfies CSSProperties,
  mapCard: {
    border,
    borderRadius: "var(--radius-card)",
    boxShadow: "var(--shadow-card)",
    margin: "0 0 0.25rem",
    overflow: "hidden",
    padding: 0,
    width: "100%",
  } satisfies CSSProperties,
  mapFrame: {
    background: "transparent",
    border: 0,
    display: "block",
    height: "13.25rem",
    margin: 0,
    padding: 0,
    width: "100%",
  } satisfies CSSProperties,
  panel: {
    boxSizing: "border-box",
    color: "var(--title-ink)",
    display: "flex",
    flex: "1 1 auto",
    flexDirection: "column",
    gap: 0,
    height: "100%",
    maxHeight: "100%",
    minHeight: 0,
    overflow: "hidden",
    width: "100%",
  } satisfies CSSProperties,
  recordCode: {
    color: "#888888",
    fontSize: "0.75rem",
    marginBottom: "0.25rem",
  } satisfies CSSProperties,
  recordExplanation: {
    fontSize: "0.95rem",
    lineHeight: 1.5,
  } satisfies CSSProperties,
  recordList: {
    margin: "0.25rem 0 0 0.75rem",
    paddingLeft: "0.75rem",
  } satisfies CSSProperties,
  recordMissing: {
    color: "#777777",
    fontStyle: "italic",
  } satisfies CSSProperties,
  regenerate: {
    background: "var(--gray-100)",
    border,
    borderRadius: "var(--radius-card)",
    color: "var(--title-ink)",
    cursor: "pointer",
    font: "inherit",
    fontSize: "0.9rem",
    fontWeight: 700,
    padding: "0.35rem 0.75rem",
  } satisfies CSSProperties,
  report: {
    display: "flex",
    flex: "1 1 auto",
    flexDirection: "column",
    gap: "1rem",
    margin: "0 auto",
    maxWidth: "68rem",
    minHeight: 0,
    overflowY: "auto",
    padding: "0.75rem var(--panel-content-padding) var(--panel-content-padding)",
    textAlign: "left",
    width: "100%",
  } satisfies CSSProperties,
  statusTable: {
    background: "var(--white)",
    border,
    borderCollapse: "separate",
    borderRadius: "var(--radius-card)",
    borderSpacing: 0,
    boxShadow: "var(--shadow-card)",
    tableLayout: "fixed",
    width: "100%",
  } satisfies CSSProperties,
  table: {
    background: "var(--white)",
    border,
    borderCollapse: "separate",
    borderRadius: "var(--radius-card)",
    borderSpacing: 0,
    tableLayout: "fixed",
    width: "100%",
  } satisfies CSSProperties,
  tableCaption: {
    color: caption,
    fontWeight: 700,
    padding: "0.5rem 0",
    textAlign: "left",
  } satisfies CSSProperties,
  tableCell: {
    borderBottom: divider,
    color: "var(--title-ink)",
    padding: "0.625rem 0.5rem",
    verticalAlign: "top",
    wordBreak: "break-word",
  } satisfies CSSProperties,
  tableHead: {
    background: "var(--gray-100)",
    borderBottom: border,
    color: "var(--title-ink)",
    fontSize: "0.9rem",
    minWidth: "5rem",
    padding: "0.625rem 0.5rem",
    textAlign: "left",
    verticalAlign: "top",
  } satisfies CSSProperties,
  tableWrap: {
    overflowX: "auto",
    width: "100%",
  } satisfies CSSProperties,
  title: {
    color: "var(--title-ink)",
    fontSize: "var(--panel-title-size)",
    fontWeight: "var(--panel-title-weight)",
    letterSpacing: "var(--panel-title-tracking)",
    lineHeight: "var(--panel-title-line-height)",
    margin: 0,
  } satisfies CSSProperties,
};
