import type { CSSProperties } from "react";

const border = "1px solid #e5e7eb";
const caption = "#18749b";

export const titleReportStyles = {
  badge(background: string | null, color: string | null): CSSProperties {
    return {
      background: background || "#e5e7eb",
      borderRadius: "9999rem",
      color: color || "#111827",
      display: "inline-block",
      fontSize: "0.875rem",
      fontWeight: 600,
      lineHeight: 1.2,
      padding: "0.25rem 0.5rem",
      whiteSpace: "nowrap",
    };
  },
  caption: {
    color: caption,
    fontWeight: 700,
    padding: "0.5rem 0",
    textAlign: "left",
  } satisfies CSSProperties,
  chainBody: {
    display: "flex",
    flexDirection: "column",
    gap: "1rem",
    padding: "0.35rem 1rem 1rem",
  } satisfies CSSProperties,
  chainList: {
    display: "flex",
    flexDirection: "column",
    gap: "0.875rem",
    width: "100%",
  } satisfies CSSProperties,
  chainSection: {
    background: "#ffffff",
    border,
    borderRadius: "0.5rem",
    boxShadow: "0 0.75rem 1.5rem rgba(15, 23, 42, 0.06)",
    margin: 0,
    overflow: "hidden",
  } satisfies CSSProperties,
  chainTrigger: {
    background: "#f0f2f7",
    border: 0,
    borderBottom: border,
    color: "#0f172a",
    cursor: "pointer",
    display: "block",
    font: "inherit",
    fontSize: "1.07rem",
    fontWeight: 700,
    lineHeight: 1.4,
    padding: "0.65rem 1rem",
    textAlign: "left",
    width: "100%",
    wordBreak: "break-word",
  } satisfies CSSProperties,
  count: {
    color: "#666666",
    fontSize: "0.95rem",
    whiteSpace: "nowrap",
  } satisfies CSSProperties,
  detailLabel: {
    color: "#6b7280",
    fontSize: "0.75rem",
    fontWeight: 600,
    marginTop: "0.5rem",
  } satisfies CSSProperties,
  empty: {
    color: "#4b5563",
    fontSize: "1rem",
  } satisfies CSSProperties,
  header: {
    alignItems: "baseline",
    display: "flex",
    flexWrap: "wrap",
    gap: "0.75rem",
    justifyContent: "space-between",
    width: "100%",
  } satisfies CSSProperties,
  headerActions: {
    alignItems: "center",
    display: "flex",
    flexWrap: "wrap",
    gap: "0.75rem",
    justifyContent: "flex-end",
  } satisfies CSSProperties,
  infoBody(color: string): CSSProperties {
    return {
      background: "#f9f9fa",
      border: `0.05rem solid ${color}`,
      borderLeft: `0.25rem solid ${color}`,
      borderRadius: "0.5rem",
      color: "#1a1b1d",
      fontSize: "0.95rem",
      lineHeight: 1.5,
      padding: "1rem",
      textAlign: "left",
    };
  },
  issueEmpty: {
    background: "#f9f9fa",
    color: caption,
    fontWeight: 700,
    margin: "0.5rem 0",
    padding: "0.5rem 0",
    textAlign: "left",
  } satisfies CSSProperties,
  link: {
    background: "transparent",
    border: 0,
    color: "#007bff",
    cursor: "pointer",
    font: "inherit",
    fontSize: "0.9375rem",
    padding: 0,
    textDecoration: "underline",
  } satisfies CSSProperties,
  mapCard: {
    border,
    borderRadius: "0.65rem",
    boxShadow: "0 0.5rem 1.2rem rgba(15, 23, 42, 0.06)",
    margin: "0 0 0.25rem",
    overflow: "hidden",
    padding: 0,
    width: "100%",
  } satisfies CSSProperties,
  mapFrame: {
    background: "transparent",
    border: 0,
    display: "block",
    height: "13.25rem",
    margin: 0,
    padding: 0,
    width: "100%",
  } satisfies CSSProperties,
  panel: {
    boxSizing: "border-box",
    color: "var(--text-main, #0f172a)",
    display: "flex",
    flex: "1 1 auto",
    flexDirection: "column",
    gap: "1rem",
    height: "100%",
    maxHeight: "100%",
    minHeight: 0,
    overflowY: "auto",
    width: "100%",
  } satisfies CSSProperties,
  recordCode: {
    color: "#888888",
    fontSize: "0.75rem",
    marginBottom: "0.25rem",
  } satisfies CSSProperties,
  recordExplanation: {
    fontSize: "0.95rem",
    lineHeight: 1.5,
  } satisfies CSSProperties,
  recordList: {
    margin: "0.25rem 0 0 0.75rem",
    paddingLeft: "0.75rem",
  } satisfies CSSProperties,
  recordMissing: {
    color: "#777777",
    fontStyle: "italic",
  } satisfies CSSProperties,
  regenerate: {
    background: "#eef2ff",
    border: 0,
    borderRadius: "0.45rem",
    color: "#334155",
    cursor: "pointer",
    font: "inherit",
    fontSize: "0.9rem",
    fontWeight: 700,
    padding: "0.35rem 0.75rem",
  } satisfies CSSProperties,
  report: {
    display: "flex",
    flexDirection: "column",
    gap: "1rem",
    margin: "0 auto",
    maxWidth: "68rem",
    textAlign: "left",
    width: "100%",
  } satisfies CSSProperties,
  statusTable: {
    background: "#ffffff",
    border,
    borderCollapse: "separate",
    borderRadius: "0.75rem",
    borderSpacing: 0,
    boxShadow: "0 0.75rem 1.5rem rgba(16, 24, 40, 0.06)",
    tableLayout: "fixed",
    width: "100%",
  } satisfies CSSProperties,
  table: {
    background: "#ffffff",
    border,
    borderCollapse: "separate",
    borderRadius: "0.5rem",
    borderSpacing: 0,
    tableLayout: "fixed",
    width: "100%",
  } satisfies CSSProperties,
  tableCaption: {
    color: caption,
    fontWeight: 700,
    padding: "0.5rem 0",
    textAlign: "left",
  } satisfies CSSProperties,
  tableCell: {
    borderBottom: "1px solid #ececec",
    color: "#1a1b1d",
    padding: "0.625rem 0.5rem",
    verticalAlign: "top",
    wordBreak: "break-word",
  } satisfies CSSProperties,
  tableHead: {
    background: "#f8fafc",
    borderBottom: border,
    color: "#1a1b1d",
    fontSize: "0.9rem",
    minWidth: "5rem",
    padding: "0.625rem 0.5rem",
    textAlign: "left",
    verticalAlign: "top",
  } satisfies CSSProperties,
  tableWrap: {
    overflowX: "auto",
    width: "100%",
  } satisfies CSSProperties,
  title: {
    color: "#0f172a",
    fontSize: "1.25rem",
    fontWeight: 700,
    margin: 0,
  } satisfies CSSProperties,
};
